### ISSUE TITLE
Dynamic Type warnings with iOS 9 deployment

### ISSUE THREAD

**Issue by zarzonis** [BalestraPatrick/WhatsNew#16]
Hi, 

I updated your library to the latest version and I get a few warning regarding dynamic type. Specifically you enabled dynamic type with iOS 9 deployment target but the dynamic type is available only on iOS 10 or later.

Here is a screenshot of the warnings.

<img width="874" alt="screen shot 2017-11-11 at 21 49 45" src="https://user-images.githubusercontent.com/6051633/32692987-19d48d3a-c72b-11e7-9159-8a3336380aa0.png">

**Comment by BalestraPatrick** [comment]
This is caused since the xib files have specified to use the dynamic font size. I guess the only solution is to specify the font on all labels programmatically inside an `if #available(iOS 10, *)`. I'll think about a clever solution or otherwise fallback to do everything programmatically :(

**Comment by zarzonis** [comment]
That's exactly the reason of the warnings. I think that the only way to solve this is to specify the font programmatically inside the `if #available` statement you already mentioned. If you come up with something better, please let me know.

**Comment by BalestraPatrick** [comment]
Fixed in release 0.3! 😄

**Comment by nixzhu** [comment]
My project with iOS 10 deployment. 

I think the `UIFont.preferredFont(forTextStyle: .headline)` for `titleLabel.font` is to small

![img_4516](https://user-images.githubusercontent.com/435208/32761952-5c6e5c0e-c931-11e7-8c9e-7ba388e92180.jpg)

I print the `font.fontDescriptor.pointSize` is 17, same as the `.body` style.

**Comment by BalestraPatrick** [comment]
@nixzhu You're right, I changed the title text style to be `.title2` so its `pointSize` is now 22 in release 0.3.1.

**Comment by nixzhu** [comment]
@BalestraPatrick `.title2` is big enough, but it's not bold.

I have try the following code is good for display:

``` swift
let fontDescriptor = UIFont.preferredFont(forTextStyle: .headline).fontDescriptor
let font = UIFont(descriptor: fontDescriptor, size: fontDescriptor.pointSize + 5)
titleLabel.font = font
```

But I think it's better if we can customize the item's font directly.

**Comment by BalestraPatrick** [comment]
Feel free to submit a PR to make the title bold and expose the font property to be customizable :)
