### ISSUE TITLE
Could I write an Android edition?

### ISSUE THREAD

**Issue by TonnyL** [BalestraPatrick/WhatsNew#20]
Hi, @BalestraPatrick ,

Your library is so well-designed and amazing!  I am an Android dev and could I write an Android edition? If the answer is positive and the android edition is done, I will express thanks to you in the main page of the lib.

Looking forward to your reply. 😉

**Comment by BalestraPatrick** [comment]
Sure, sounds good! Let me know when you have published it 👍

**Comment by TonnyL** [comment]
Hi, @BalestraPatrick 

I've finished the job. Here it is: https://github.com/TonnyL/WhatsNew . But it is not pretty as yours 😂.

**Comment by BalestraPatrick** [comment]
Looks nice, I'll add it to the README! 👍
