### ISSUE TITLE
repeat appearing 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [BalestraPatrick/WhatsNew#21]
I tried this code but it keeps coming again and again when I click on continue. I implement it in viewDidAppear

 ```
let whatsNew = WhatsNewViewController(items: [
                WhatsNewItem.image(title: "Nice Icons", subtitle: "Completely customize colors, texts and icons.", image: #imageLiteral(resourceName: "lgoJaee")),
                WhatsNewItem.image(title: "Such Easy", subtitle: "Setting this up only takes 2 lines of code, impressive you say?", image: #imageLiteral(resourceName: "lgoJaee")),
                WhatsNewItem.image(title: "Very Sleep", subtitle: "It helps you get more sleep by writing less code.", image: #imageLiteral(resourceName: "lgoJaee")),
                WhatsNewItem.text(title: "Text Only", subtitle: "No icons? Just go with plain text."),
                ])
            whatsNew.titleText = "What's New"
            whatsNew.buttonText = "Continue"
            present(whatsNew, animated: true, completion: nil)
```

how can I dismiss it and never appear again?

**Comment by BalestraPatrick** [comment]
You should check if you can present the view first like it is shown in the [Example app](https://github.com/BalestraPatrick/WhatsNew/blob/master/Example/WhatsNew/ViewController.swift#L17).

More precisely, wrap your code in an if statement:
```swift
if WhatsNew.shouldPresent() {
  // Your code here
}
```

**Comment by AbdulazizAlmohsen** [comment]
I get this error` Module 'WhatsNew' has no member named 'shouldPresent'` even in the example app

**Comment by BalestraPatrick** [comment]
You should run `pod update` to make sure you have the latest version. I was just able to create a project from scratch and I saw no error.

**Comment by AbdulazizAlmohsen** [comment]
great thank you 👍
