### ISSUE TITLE
.majorVersion presentation option does not display update info when previous version is nil

### ISSUE THREAD

**Issue by funkenstrahlen** [BalestraPatrick/WhatsNew#22]
My app does receive a major update to 3.0 and I did add `WhatsNew` now to show users what changed.

However when I configure the WhatsNewController to be displayed for `.majorVersion` it is not displayed because your method to calculate whether to display the update message is incorrect. It fails if the user defaults key for previous version is not set.

**Comment by BalestraPatrick** [comment]
Hey! I don’t have a lot of time in the next few days to check this issue and release a fix. If you can’t wait for me to work it, you’re welcome to try and open a PR. 👍
