### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by sdevo619** [BalestraPatrick/WhatsNew#25]
There are several errors that this is currently generating please update. Thank you!

**Comment by BalestraPatrick** [comment]
@sdevo619 Can you please specify which errors are being generated? Some more accurate information would help fixing the issue faster 😀

**Comment by sdevo619** [comment]
Sorry about the delayed response. Immediately after installing it in my project file it threw several errors in XCode. I’m running 9.3 just FYI. I will reinstall your pod  into my project and see if I can get you the actual specific errors. Let me know if you find anything yourself after setting up a fresh project using cocoa pods. Thanks!

Spencer Koltun

**Comment by sdevo619** [comment]
I just had a chance to test it again and theses are the errors I’m seeing. Let me know when you have a chance to fix them. Thank you very much. Looking forward to using this!!!

**Comment by BalestraPatrick** [comment]
Hey @sdevo619, I don't see any errors in your last comment. Do you mind attaching an image or a code snippet?

**Comment by sdevo619** [comment]
Here they are again. I attached a screenshot to my last email. Not sure why you aren’t seeing it. Here it is again. 





Spencer Koltun

**Comment by BalestraPatrick** [comment]
@sdevo619 Seems like you're replying to this thread via email and it isn't working properly. Can you try using the web UI?

**Comment by sdevo619** [comment]
Sorry about that. Here is a reply Im posting through GitHub directly.
![image](https://user-images.githubusercontent.com/7008354/39606664-645ab81e-4eeb-11e8-9afb-3c4a9bc911a6.png)

**Comment by BalestraPatrick** [comment]
I tried generating a new project using CocoaPods and it's working as expected here. Those errors look weird to me, they seem like you don't have the correct SWIFT_VERSION set up in your build settings maybe?

**Comment by sdevo619** [comment]
Thank you very much. I’ll take a look and see what I can come up with. I’ll update you after I have had a chance to investigate a bit more. Thanks for the tip. 

Spencer Koltun

**Comment by sdevo619** [comment]
You can close this ticket out. Thanks for the help. It appears to have been an issue with me needing to complete the Swift 4 conversion for that project. I do have one important question though. Is there a way to customize the background color for the WhatsNew Screen? As my app uses a dark color palette using a white screen inside it is not ideal. It seams like it should be pretty easy to add that for you as its just using a tableview it looks like. Please keep me posted as I will need to find something else if using a black background isn't availble. Thanks again!!

**Comment by BalestraPatrick** [comment]
That's great to hear. To change the background color of the `WhatsNew` you can simply set it in this way: `whatsNew.view.backgroundColor = .black`

**Comment by sdevo619** [comment]
Patrick,
Thanks again for the lightning fast reply’s and for the help. One more question for you. I have the background on the what’s new VC set to black now, but the status bar is still showing as black text. I tried using 

whatsNew.modalPresentationCaptureStatusBarAppearance = true

 as the VC it’s being presented over has the status bar set to white text, but it’s not changing the status bar to white like I would expect, so I figure I should probably ask you before I spent a bunch of time troubleshooting it. Thanks again!!!


Spencer Koltun

**Comment by BalestraPatrick** [comment]
There are many possible ways to do that, you can make your status bar style not based on the view controller by modifying a key in the `Info.plist`, I think that's what you want if your whole app is dark.

**Comment by sdevo619** [comment]
I have considered that, but there are several screens in the app where I need to be able change the status bar text color. I know there are a few different ways, but I would ideally like to be to handle this as I’m presenting the what’s new Vc? What would be the best way to accomplish this, as I can’t override the status bar on launch easily due to the circumstances. 

Spencer Koltun
