### ISSUE TITLE
Not able to change "titleFont and "itemSubtitleFont"

### ISSUE THREAD

**Issue by inderpal-upgame** [BalestraPatrick/WhatsNew#34]

**Comment by samuelail** [comment]
It's in the docs.

public var itemTitleFont: UIFont = UIFont.systemFont(ofSize: 20, weight: .bold)

/// Subtitle font of the feature items
public var itemSubtitleFont: UIFont = UIFont.systemFont(ofSize: 16, weight: .regular)
