### ISSUE TITLE
Incorrect Apostophe

### ISSUE THREAD

**Issue by mdznr** [BalestraPatrick/WhatsNew#5]
The apostrophe in “What’s New” should be angled/curly, instead of the straight/typewriter apostrophe.

' vs ’

**Comment by BalestraPatrick** [comment]
Would you mind opening a PR for this?

**Comment by mdznr** [comment]
I don’t think I can submit a PR at this time.

The fix is on [WhatsNewViewController.swift:19](https://github.com/BalestraPatrick/WhatsNew/blob/master/WhatsNew/WhatsNewViewController.swift#L19):

`public var titleText: String = "What's New" {`

should instead be:

`public var titleText: String = "What’s New" {`

It should also be using localized strings:

`public var titleText: String = NSLocalizedString("What’s New", comment: "The default title of the “What’s New” view.") {`

**Comment by BalestraPatrick** [comment]
Just fixed this. The `NSLocalizedString` can be assigned manually when using the library.

**Comment by mdznr** [comment]
Seems unusual to have a default value but not have it localized.

**Comment by mdznr** [comment]
All UI strings should be run through `NSLocalizedString`, unless, of course, it’s user-generated content.
