### ISSUE TITLE
Align title and subtitles

### ISSUE THREAD

**Issue by mdznr** [BalestraPatrick/WhatsNew#6]
The text for titles and subtitles should be left-aligned instead of wrapping around the icons. This will make it easier to visually scan.

**Comment by BalestraPatrick** [comment]
Apple's "What's New" screens do the same as we do and I think the current design makes sense.

**Comment by mdznr** [comment]
I’m very familiar with this topic and can say that’s definitely not true. Which app are you referencing that puts the subtitle below the icon and title?
