### ISSUE TITLE
Minimum version 8.0/9.0

### ISSUE THREAD

**Issue by brightsider** [BalestraPatrick/WhatsNew#8]

**Comment by BalestraPatrick** [comment]
What are you asking here exactly?

**Comment by brightsider** [comment]
Can you change minimal deployment version to 9.0 or 8.0 instead of 9.3?

**Comment by BalestraPatrick** [comment]
Changing it to 9.0 is possible I think. Would you like to submit a PR for this change?

**Comment by brightsider** [comment]
I think you should to update podspec for CocoaPods after changes. You can change it before send update to CocoaPods

**Comment by ghost** [comment]
This is an awesome library. Changing the minimum deployment version to 9.0 will be really helpful.

**Comment by ghost** [comment]
Thanks @BalestraPatrick
